SosBodyApp/Controllers/CalendarController.cs
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

using Newtonsoft.Json;
using System.IO;
using System.Net;
using System.Net.Http;
using System.Web.UI;
using System.Web.UI.WebControls;

using Google.Apis.Auth.OAuth2;
using Google.Apis.Calendar.v3;
using Google.Apis.Calendar.v3.Data;
using Google.Apis.Services;
using Google.Apis.Util.Store;
using Google.Apis.Plus.v1;
using Google.Apis.Plus.v1.Data;


//using Google.GData.Calendar;
//using Google.GData.Extensions;
//using Google.GData.Client;

using SOSBody.Helpers.Google;
using System.Threading.Tasks;
using Google.Apis.Auth.OAuth2.Responses;
using System.Threading;

namespace SOSBody.Controllers
{
    public class GoogleUserOutputData
    {
        public string id { get; set; }
        public string name { get; set; }
        public string given_name { get; set; }
        public string email { get; set; }
        public string picture { get; set; }
    }

    public class GooglePlusAccessToken
    {
        public string access_token { get; set; }
        public string token_type { get; set; }
        public int expires_in { get; set; }
        public string id_token { get; set; }
        public string refresh_token { get; set; }
    }

    public class CalendarController : Controller
    {
        protected string googleplus_client_id = "248882027328-477sa4fs2l45720f8slbuk0q5vtr0u53.apps.googleusercontent.com";    // Replace this with your Client ID
        protected string googleplus_client_secret = "eLQfi0scc1OLeMPJzMmsBefE";                                                // Replace this with your Client Secret
        protected string googleplus_redirect_url = "http://localhost:51672/Calendar/";                                         // Replace this with your Redirect URL; Your Redirect URL from your developer.google application should match this URL.
        protected string Parameters;


        //
        // GET: /Calendar/


        public async Task<ActionResult> Index()
        {
            if (Session.Contents.Count > 0)
            {
                if (Session["loginWith"] != null)
                {
                    if (Session["loginWith"].ToString() == "google")
                    {
                        try
                        {
                            var url = Request.Url.Query;
                            if (url != "")
                            {
                                string queryString = url.ToString();
                                char[] delimiterChars = { '=' };
                                string[] words = queryString.Split(delimiterChars);
                                string code = words[1];

                                if (code != null)
                                {
                                    //get the access token 
                                    HttpWebRequest webRequest = (HttpWebRequest)WebRequest.Create("https://accounts.google.com/o/oauth2/token");
                                    webRequest.Method = "POST";
                                    Parameters = "code=" + code + "&client_id=" + googleplus_client_id + "&client_secret=" + googleplus_client_secret + "&redirect_uri=" + googleplus_redirect_url + "&grant_type=authorization_code";
                                    byte[] byteArray = System.Text.Encoding.UTF8.GetBytes(Parameters);
                                    webRequest.ContentType = "application/x-www-form-urlencoded";
                                    webRequest.ContentLength = byteArray.Length;
                                    Stream postStream = webRequest.GetRequestStream();
                                    // Add the post data to the web request
                                    postStream.Write(byteArray, 0, byteArray.Length);
                                    postStream.Close();

                                    WebResponse response = webRequest.GetResponse();
                                    postStream = response.GetResponseStream();
                                    StreamReader reader = new StreamReader(postStream);
                                    string responseFromServer = reader.ReadToEnd();

                                    GooglePlusAccessToken serStatus = JsonConvert.DeserializeObject<GooglePlusAccessToken>(responseFromServer);

                                    if (serStatus != null)
                                    {
                                        string accessToken = string.Empty;
                                        accessToken = serStatus.access_token;

                                        if (!string.IsNullOrEmpty(accessToken))
                                        {
                                            // This is where you want to add the code if login is successful.
                                            //getgoogleplususerdataSer(accessToken);

                                            UserCredential credential = GoogleWebAuthorizationBroker.AuthorizeAsync(
                                               new ClientSecrets
                                               {
                                                   ClientId = googleplus_client_id,
                                                   ClientSecret = googleplus_client_secret,
                                               },
                                               new[] { CalendarService.Scope.Calendar },
                                               "user",
                                               CancellationToken.None).Result;


                                            // Create the service.
                                            CalendarService service = new CalendarService(new BaseClientService.Initializer()
                                            {
                                                HttpClientInitializer = credential,
                                                ApplicationName = "Calendar API Sample",
                                            });

                                            // Fetch the list of calendar list
                                            //IList<CalendarListEntry> list = service.CalendarList.List().Execute().Items;
                                            //CalendarListEntry entry = list[0];

                                            //EventsResource.ListRequest events = service.Events.List(list[0].Id);

                                            // Define parameters of request.
                                            EventsResource.ListRequest request = service.Events.List("primary");
                                            request.TimeMin = DateTime.Now;
                                            request.ShowDeleted = false;
                                            request.SingleEvents = true;
                                            request.MaxResults = 10;
                                            request.OrderBy = EventsResource.ListRequest.OrderByEnum.StartTime;

                                            // List events.
                                            Events events = request.Execute();
                                            List<Event> sosBodyEventList = new List<Event>();

                                            if (events.Items != null && events.Items.Count > 0)
                                            {
                                                foreach (var eventItem in events.Items)
                                                {
                                                    if (eventItem.Summary != null && eventItem.Summary.ToUpper() == "SOSBODY")
                                                        sosBodyEventList.Add(eventItem);

                                                    //string when = eventItem.Start.DateTime.ToString();
                                                    //if (String.IsNullOrEmpty(when))
                                                    //{
                                                    //    when = eventItem.Start.Date;
                                                    //}
                                                    //Console.WriteLine("{0} ({1})", eventItem.Summary, when);
                                                }
                                            }

                                            return Redirect("/Admin/Calendar");
                                        }
                                        else
                                        { }
                                    }
                                    else
                                    { }
                                }
                                else
                                { }
                            }
                        }
                        catch (Exception ex)
                        {
                            string s = ex.Message;
                            //throw new Exception(ex.Message, ex);
                            //Response.Redirect("index.aspx");
                        }
                    }
                }

            }
            //else
            {
                var Googleurl = "https://accounts.google.com/o/oauth2/auth?response_type=code&redirect_uri=" + googleplus_redirect_url + "&scope=https://www.googleapis.com/auth/userinfo.email%20https://www.googleapis.com/auth/userinfo.profile&client_id=" + googleplus_client_id;
                Session["loginWith"] = "google";
                Response.Redirect(Googleurl);
            }

            



            //IList  list = service.SynchronizeEvents();
            return View();
        }


        private async void getgoogleplususerdataSer(string access_token)
        {
            try
            {
                HttpClient client = new HttpClient();

SosBodyApp/Views/Admin/Billing.cshtml
@using SosBody.Models;
@model SosBody.Models.InvoiceDetailModel
@{
    ViewBag.Title = "SOS Body - Fakturační údaje";
}

@section menuItems {
    @Html.ActionLink("ODHLÁSIT SE", "Logout", "Account", null, new { @class = "w3-bar-item w3-button w3-padding-large " })
    @*@Html.ActionLink("POZVAT KOLEGU", "Pozvani", "Admin", null, new { @class = "w3-bar-item w3-button w3-padding-large " })*@
    @*<div class="dropmenu-wrapper">
        <a class="w3-bar-item w3-button w3-padding-large" href="javascript:void(0)">PROFIL</a>
        <div class="dropmenu-content">
            @Html.ActionLink("MŮJ PROFIL", "HomeMedic", "Admin", null, new { @class = "w3-bar-item" })
            @Html.ActionLink("ORDINACE", "HomeOffice", "Admin", null, new { @class = "w3-bar-item" })
            @Html.ActionLink("FAKTURAČNÍ ÚDAJE", "HomeBilling", "Admin", null, new { @class = "w3-bar-item" })
            @Html.ActionLink("NASTAVENÍ KALENDÁŘE", "CalendarSettings", "Admin", null, new { @class = "w3-bar-item" })
        </div>
    </div>*@
}

<!-- Page content -->
<div class="w3-container w3-content w3-padding-64" style="max-width:680px" id="contact">
    @*<h2 class="w3-wide w3-center h2_sos_header">FAKTURAČNÍ ÚDAJE</h2>*@

    <div class="w3-row w3-padding-32 sos-tabs">
        <div class="w3-center">
            @Html.ActionLink("PROFIL", "HomeMedic", "Admin", null, new { @class = "" })
        </div>
        <div class="w3-center">
            @Html.ActionLink("ORDINACE", "HomeOffice", "Admin", null, new { @class = "" })
        </div>
        <div class="w3-center">
            @Html.ActionLink("FAKTURAČNÍ ÚDAJE", "HomeBilling", "Admin", null, new { @class = "current" })
        </div>
        <div class="w3-center">
            @Html.ActionLink("NASTAVENÍ KALENDÁŘE", "CalendarSettings", "Admin", null, new { @class = "" })
        </div>
        <div class="w3-center">
            @Html.ActionLink("KALENDÁŘ", "Calendar", "Admin", null, new { @class = "" })
        </div>
    </div>

    <div class="w3-row w3-padding-32" >
        @Html.ValidationSummary(false)
        @using (Html.BeginForm(null, null, FormMethod.Post))
        {
            @Html.HiddenFor(x => x.Id)
            @Html.HiddenFor(x => x.UserId)
            @Html.HiddenFor(x => x.Accept)

            <div class="w3-row-padding m12" style="margin:0 -16px 8px -16px">
                <div class="w3-third left_col">
                    IČ
                </div>
                <div class="w3-twothird right_col">
                    @Html.TextBoxFor(x => x.IdentifyNo, new { @class = "reg_form", @maxlength = 8, id = "ico" })
                </div>
            </div>
            <div class="w3-row-padding m12" style="margin:0 -16px 8px -16px">
                <div class="w3-third left_col">
                    
                </div>
                <div class="w3-twothird right_col">
                    <div class="button" id="lookup">VYHLEDAT DLE IČ</div>
                </div>
            </div>


            <div class="w3-row-padding m12" style="margin:0 -16px 8px -16px">
                <div class="w3-third left_col">
                    Název společnosti
                </div>
                <div class="w3-twothird right_col">
                    @Html.TextBoxFor(x => x.Name, new { @class = "reg_form", @style = "padding-top:0px;" })
                </div>
            </div>
            <div class="w3-row-padding m12" style="margin:0 -16px 8px -16px">
                <div class="w3-third left_col">
                    Adresa
                </div>
                <div class="w3-twothird right_col">
                    @Html.TextBoxFor(x => x.Address, new { @class = "reg_form" })
                </div>
            </div>
            <div class="w3-row-padding m12" style="margin:0 -16px 8px -16px">
                <div class="w3-third left_col">
                    Telefon
                </div>
                <div class="w3-twothird right_col">
                    @Html.DropDownListFor(x => x.PhonePrefix, new SelectList(Model.PhonePrefixList, "Value", "Text"), new { @class = "reg_form", @style = "width:80px;", @onchange = "FillPhoneNumberLength(this.value)" })
                    @Html.TextBoxFor(x => x.Phone, new { @class = "reg_form", @style = "width:100px;", @maxlength = Model.PhonePrefixLength})
                </div>
            </div>
            <div class="w3-row-padding m12" style="margin:0 -16px 8px -16px">
                <div class="w3-third left_col">
                    Email
                </div>
                <div class="w3-twothird right_col">
                    @Html.TextBoxFor(x => x.Email, new { @class = "reg_form" })
                </div>
            </div>
            <div class="w3-row-padding m12" style="margin:0 -16px 8px -16px">
                <div class="w3-third left_col">
                    Bankovní účet
                </div>
                <div class="w3-twothird right_col">
                    @Html.TextBoxFor(x => x.Prefix, new { @class = "reg_form", @style = "width:70px;", @maxlength = 6 }) -
                    @Html.TextBoxFor(x => x.BankAccount, new { @class = "reg_form", @style = "width:100px;", @maxlength = 10 }) / 
                    @Html.DropDownListFor(x => x.Postfix, new SelectList(Model.PostfixList, "Value", "Text"), "", new { @class = "reg_form", @style = "width:80px;" })
                    <p style="color:red;">@Model.ErrorMessage</p>
                    @*@Html.ValidationMessageFor(x => x.Postfix, "", new { @class = "text-danger" })*@
                </div>
            </div>
            <div class="w3-row-padding m12" style="margin:0 -16px 8px -16px">
                <div class="w3-third left_col">
                    
                </div>
                <div class="w3-twothird right_col">
                    
                </div>
            </div>
            <div class="w3-row-padding m12" style="margin:0 -16px 8px -16px">
                <div class="w3-third left_col">
                    DIČ
                </div>
                <div class="w3-twothird right_col">
                    @Html.TextBoxFor(x => x.TaxIdentifyNo, new { @class = "reg_form", @maxlength = 10 })
                </div>
            </div>
            <div class="w3-row-padding m12" style="margin:0 -16px 8px -16px">
                <div class="w3-third left_col">
                    
                </div>
                <div class="w3-twothird right_col">

                </div>
            </div>

            <div class="w3-row-padding m12" style="margin:0 -16px 8px -16px">
                <div class="w3-third">
                    &nbsp;
                </div>
                <div class="w3-third">
                    @Html.ActionLink("ZPĚT", "HomeBilling", null, new { @class = "button" })
                </div>
                <div class="w3-third">
                    <button type="submit" class="button">ULOŽIT</button>
                </div>
            </div>

        }
    </div>
</div>

<script>

    $("#lookup").click(function () {
        $.ajax({
            type: "POST",
            url: "/Admin/LookUp",
            data: ({ ico: $('#ico').val(), redirect: "Billing", email: $('#Email').val(), phone: $('#Phone').val(), phonePrefix: $('#PhonePrefix').val(), prefix: $('#Prefix').val(), bankAccount: $('#BankAccount').val(), postfix: $('#Postfix').val(), taxIdentifyNo: $('#TaxIdentifyNo').val() }),
            success: function (result) {
                window.location.href = result.Url;
        }
        });
    });

        function FillPhoneNumberLength(val) {
            $.ajax({
                url: '/Admin/GetPhoneNumberLength',
                type: "POST",
                dataType: "JSON",
                data: { prefix: val },
                success: function (result) {
                    $('#Phone').attr("maxlength", result.Length);
                }
            });
        }

</script>

SosBodyApp/Views/Admin/CalendarSettings.cshtml
@using SosBody.Models;
@model SosBody.Models.CalendarSettingsModel
@{
    ViewBag.Title = "Profil fyzioterapeuta";
}


@section menuItems {
    @Html.ActionLink("ODHLÁSIT SE", "Logout", "Account", null, new { @class = "w3-bar-item w3-button w3-padding-large " })
    @*@Html.ActionLink("POZVAT KOLEGU", "Pozvani", "Admin", null, new { @class = "w3-bar-item w3-button w3-padding-large " })*@
    @*<div class="dropmenu-wrapper">
        <a class="w3-bar-item w3-button w3-padding-large" href="javascript:void(0)">PROFIL</a>
        <div class="dropmenu-content">
            @Html.ActionLink("MŮJ PROFIL", "HomeMedic", "Admin", null, new { @class = "w3-bar-item" })
            @Html.ActionLink("ORDINACE", "HomeOffice", "Admin", null, new { @class = "w3-bar-item" })
            @Html.ActionLink("FAKTURAČNÍ ÚDAJE", "HomeBilling", "Admin", null, new { @class = "w3-bar-item" })
            @Html.ActionLink("NASTAVENÍ KALENDÁŘE", "CalendarSettings", "Admin", null, new { @class = "w3-bar-item" })
        </div>
    </div>
    @Html.ActionLink("KALENDÁŘ", "Calendar", "Admin", null, new { @class = "w3-bar-item w3-button w3-padding-large " })*@
}   

<!-- Page content -->
<div class="w3-container w3-content w3-padding-64" style="max-width:800px" id="contact">
    @*<h2 class="w3-wide w3-center h2_sos_header">NASTAVENÍ KALENDÁŘE</h2>*@

    <div class="w3-row w3-padding-32 sos-tabs">
        <div class="w3-center">
            @Html.ActionLink("PROFIL", "HomeMedic", "Admin", null, new { @class = "" })
        </div>
        <div class="w3-center">
            @Html.ActionLink("ORDINACE", "HomeOffice", "Admin", null, new { @class = "" })
        </div>
        <div class="w3-center">
            @Html.ActionLink("FAKTURAČNÍ ÚDAJE", "HomeBilling", "Admin", null, new { @class = "" })
        </div>
        <div class="w3-center">
            @Html.ActionLink("NASTAVENÍ KALENDÁŘE", "CalendarSettings", "Admin", null, new { @class = "current" })
        </div>
        <div class="w3-center">
            @Html.ActionLink("KALENDÁŘ", "Calendar", "Admin", null, new { @class = "" })
        </div>
    </div>

    <div class="w3-row w3-padding-32">
        @Html.ValidationSummary(false)
        @using (Html.BeginForm())
        {
            @Html.HiddenFor(x => x.Id)
            @Html.HiddenFor(x => x.UserId)
            @Html.HiddenFor(x => x.OfficeId)

            if (Model.Offices.Count > 1)
            {
                <div class="w3-display-container w3-center w3-padding-32">
                    <strong>Ordinace:</strong>
                    @foreach (var office in Model.Offices)
                    {
                        if (Model.CurrentCalendarId == office.Id)
                        {
                            @Html.ActionLink(office.Name, "CalendarSettings", "Admin", new { calIndex = office.Id }, new { @style = "padding-left:20px; color:rgb(127, 175, 61);" }) //#015217
                        }
                        else
                        {
                            @Html.ActionLink(office.Name, "CalendarSettings", "Admin", new { calIndex = office.Id }, new { @style = "padding-left:20px; color:#D0D0D0;" })
                        }
                    }
                </div>
            }

            <div class="w3-col m4 w3-large w3-margin-bottom">
                <img class="img-circle" src="@Url.Content(Model.ProfileImage)" width="200" height="200">
            </div>
            <div class="w3-col m8">

                <div class="w3-row-padding" style="margin:0 -16px 8px -16px">
                    <div class="w3-third left_col">
                        Sazba 30 min:
                    </div>
                    <div class="w3-twothird right_col">
                        @Html.TextBoxFor(x => x.Price30, new { @class = "reg_form", @style = "width:70px;", @maxlength = "5" })
                        Kč
                        @*@Html.ValidationMessageFor(x => x.Price30)*@
                    </div>
                </div>
                <div class="w3-row-padding" style="margin:0 -16px 8px -16px">
                    <div class="w3-third left_col">
                        Sazba 60 min:
                    </div>
                    <div class="w3-twothird right_col">
                        @Html.TextBoxFor(x => x.Price60, new { @class = "reg_form", @style = "width:70px;", @maxlength = "5" })
                        Kč
                        @*@Html.ValidationMessageFor(x => x.Price60)*@
                    </div>
                </div>
                <div class="w3-row-padding" style="margin:0 -16px 8px -16px">
                    <div class="w3-third left_col">
                        Sazba 90 min:
                    </div>
                    <div class="w3-twothird right_col">
                        @Html.TextBoxFor(x => x.Price90, new { @class = "reg_form", @style = "width:70px;", @maxlength = "5" })
                        Kč
                        @*@Html.ValidationMessageFor(x => x.Price90)*@
                    </div>
                </div>
                @*<div class="w3-row-padding" style="margin:0 -16px 8px -16px">
                    <div class="w3-third left_col">
                        Barva ordinace:
                    </div>
                    <div class="w3-twothird right_col">
                       
                    </div>
                </div>*@


                <div class="w3-row-padding" style="margin:0 -16px 8px -16px">
                    <div class="w3-third left_col">
                        @*Propojení*@
                    </div>
                    <div class="w3-twothird right_col">
                        @*@Html.CheckBoxFor(x => x.GoogleCalendarConnection /*, new { @disabled = "disabled" }*/)
                        S kalendářem Google*@
                    </div>
                </div>

                <div class="w3-row-padding" style="margin:0 -16px 8px -16px">
                    <div class="w3-quarter">
                        &nbsp;
                    </div>
                    <div class="w3-twothird">
                        <div class="w3-half">
                            <button type="submit" class="button">ULOŽIT</button>
                        </div>
                        <div class="w3-half">

                        </div>
                    </div>
                </div>
            </div>
        }
    </div>
</div>

@*http://www.aspdotnet-pools.com/2016/03/multiselect-dropdownlist-using-jquery.html*@

SosBodyApp/Views/Admin/DeleteProfileError.cshtml
@using SosBody.Models;
@model SosBody.Models.ConfirmPasswordModel
@{
    ViewBag.Title = "SOS Body";
}

@section menuItems {
    <div class="dropmenu-wrapper">
        <a class="w3-bar-item w3-button w3-padding-large" href="javascript:void(0)">REGISTROVAT SE ZDARMA</a>
        <div class="dropmenu-content">
            @Html.ActionLink("FYZIOTERAPEUT", "RegisterMedic", "Admin", null, new { @class = "w3-bar-item w3-button w3-padding-large" })
            @Html.ActionLink("PACIENT", "RegisterPatient", "Admin", null, new { @class = "w3-bar-item w3-button w3-padding-large" })
        </div>
    </div>
    @Html.ActionLink("PŘIHLÁSIT SE", "Login", "Account", null, new { @class = "w3-bar-item w3-button w3-padding-large " })
}

<!-- Page content -->
<div class="w3-container w3-content w3-padding-64" style="max-width:700px" id="contact">
    <h2 class="w3-wide w3-center h2_sos_header">VYMAZÁNÍ PROFILU</h2>
    <div class="w3-row w3-padding-32 w3-center">
        <div class="w3-col m12">
           Při smazání profilu došlo k chybě. Kontaktujte prosím administrátora na e-mailové adrese info@sosbody.cz      
        </div>
    </div>
</div>

<script>

    function RedirectWithEmail() {
        var param = document.getElementById("Email");
        window.location.href = "../../Account/Login?email=" + param.value;
    }
</script>

SosBodyApp/Views/Admin/FormPatient.cshtml
@using SosBody.Models;
@model SosBody.Models.FormPatientModel
@{
    ViewBag.Title = "SOS Body";
}

<h2>Form Patient</h2>
@*@Html.ValidationSummary(false)*@
@using (Html.BeginForm())
{
    @Html.HiddenFor(x => x.Id)
    @Html.HiddenFor(x => x.UserId)
    <div class="form-group">
        @Html.LabelFor(x => x.Phone)
        @Html.TextBoxFor(x => x.Phone, new { @class = "form-control" })
    </div>
    @*<div class="form-group">
        @Html.LabelFor(x => x.PostalCode)
        @Html.TextBoxFor(x => x.PostalCode, new { @class = "form-control" })
    </div>
    <div class="form-group">
        @Html.LabelFor(x => x.City)
        @Html.TextBoxFor(x => x.City, new { @class = "form-control" })
    </div>*@
    <button type="submit" class="btn btn-primary">Save</button>
    @Html.ActionLink("Cancel", "HomePatient", null, new { @class = "btn btn-default" })
}

SosBodyApp/Views/Admin/HomeOffice.cshtml
@using SosBody.Models;
@model SosBody.Models.FormMedicModel
@{
    ViewBag.Title = "SOS Body";
}

@section menuItems {
    @Html.ActionLink("ODHLÁSIT SE", "Logout", "Account", null, new { @class = "w3-bar-item w3-button w3-padding-large " })
    @*@Html.ActionLink("POZVAT KOLEGU", "Pozvani", "Admin", null, new { @class = "w3-bar-item w3-button w3-padding-large " })*@
    @*<div class="dropmenu-wrapper">
        <a class="w3-bar-item w3-button w3-padding-large" href="javascript:void(0)">PROFIL</a>
        <div class="dropmenu-content">
            @Html.ActionLink("MŮJ PROFIL", "HomeMedic", "Admin", null, new { @class = "w3-bar-item" })
            @Html.ActionLink("ORDINACE", "HomeOffice", "Admin", null, new { @class = "w3-bar-item" })
            @Html.ActionLink("FAKTURAČNÍ ÚDAJE", "HomeBilling", "Admin", null, new { @class = "w3-bar-item" })
            @Html.ActionLink("NASTAVENÍ KALENDÁŘE", "CalendarSettings", "Admin", null, new { @class = "w3-bar-item" })
        </div>
    </div>
    @Html.ActionLink("KALENDÁŘ", "Calendar", "Admin", null, new { @class = "w3-bar-item w3-button w3-padding-large " })*@
}

<!-- Page content -->
<div class="w3-container w3-content w3-padding-64" style="max-width:800px" id="contact">
    <div class="w3-row w3-padding-32 sos-tabs">
        <div class="w3-center">
            @Html.ActionLink("PROFIL", "HomeMedic", "Admin", null, new { @class = "" })
        </div>
        <div class="w3-center">
            @Html.ActionLink("ORDINACE", "HomeOffice", "Admin", null, new { @class = "current" })
        </div>
        <div class="w3-center">
            @Html.ActionLink("FAKTURAČNÍ ÚDAJE", "HomeBilling", "Admin", null, new { @class = "" })
        </div>
        <div class="w3-center">
            @Html.ActionLink("NASTAVENÍ KALENDÁŘE", "CalendarSettings", "Admin", null, new { @class = "" })
        </div>
        <div class="w3-center">
            @Html.ActionLink("KALENDÁŘ", "Calendar", "Admin", null, new { @class = "" })
        </div>
    </div>

    <div class="w3-row w3-padding-32">
        <div class="w3-col m4 w3-large w3-margin-bottom">
            <img class="img-circle" src="@Url.Content(Model.ProfileImage)" width="200" height="200">
        </div>
        <div class="w3-col m8">
            
            @foreach (OfficeDetailModel office in Model.Offices)
            {
                <div class="w3-row-padding" style="margin:0 -16px 8px -16px">
                    <div class="w3-third left_col">
                        @office.Name
                    </div>
                    <div class="w3-twothird right_col">
                        @office.Street @office.StreetNo, @office.City@*, @office.PostalCode*@
                    </div>
                </div>
            }

            <div class="w3-padding-32" style="margin:0 -16px 8px -16px">
                <div class="w3-third">
                    &nbsp;
                </div>
                <div class="w3-twothird">
                    <div class="w3-half">
                        @Html.ActionLink("DETAIL ORDINACE", "Office", null, new { @class = "button" })
                    </div>
                    <div class="w3-half">
                    </div>
                </div>
            </div>

        </div>
    </div>
</div>

SosBodyApp/Views/Admin/HomePatient.cshtml
@using SosBody.Models;
@model SosBody.Models.HomePatientModel
@{
    ViewBag.Title = "SOS Body";
}

@section menuItems {
    @Html.ActionLink("ODHLÁSIT SE", "Logout", "Account", null, new { @class = "w3-bar-item w3-button w3-padding-large " })
}

<!-- Page content -->
<div class="w3-container w3-content w3-padding-64" style="max-width:800px" id="contact">
    <h2 class="w3-wide w3-center h2_sos_header">PROFIL PACIENTA</h2>

    <div class="w3-row w3-padding-32 sos-tabs">
        <div class="w3-center">
            @Html.ActionLink("PROFIL", "HomePatient", "Admin", null, new { @class = "current" })
        </div>
        <div class="w3-center">
            @Html.ActionLink("HISTORIE", "HistoryPatient", "Admin", null, new { @class = "" })
        </div>
    </div>


    <div class="w3-row">
        @Html.ActionLink(
                        "Smazat profil",
                        "DeletePatientProfile",
                        "Admin",
                        new { userId = Model.UserId },
                        new { onclick = "return confirm('Opravdu si přejete vymazat tento profil?')", @class = "left_col" })
    </div>


</div>

SosBodyApp/Views/Admin/Login.cshtml
@using SosBody.Models;
@model SosBody.Models.CreateModel
@{
    ViewBag.Title = "Login";
}

<h2>Login</h2>
@using (Html.BeginForm())
{
    <div class="form-group">
        @Html.LabelFor(x => x.Username)
        @Html.TextBoxFor(x => x.Username, new { @class = "form-control" })
    </div>
    <div class="form-group">
        @Html.LabelFor(x => x.Password)
        @Html.PasswordFor(x => x.Password, new { @class = "form-control" })
    </div>
    <button type="submit" class="btn btn-primary">Login</button>
    @*@Html.ActionLink("Cancel", "Index", null, new { @class = "btn btn-default" })*@
}