SosBodyApp/Models/DashboardViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace SosBody.Models
{
    public class BasicMedicsModel
    {
        public string UserId { get; set; }
        public string Name { get; set; }
        public string LastName { get; set; }
        public bool IsMedicPersonalData { get; set; }
        public bool IsMedicOfficeData { get; set; }
        public bool IsMedicInviceData { get; set; }
        public bool IsProfileImage { get; set; }
        public int FreeDates { get; set; }
        public int TotalDates { get; set; }
        public int TotalOrders { get; set; }

    }

    public class AllMedicsModel
    {
        public List<BasicMedicsModel> Medics { get; set; }
        public int CompletedRegistrations { get; set; }
        public int IncompletedRegistrations { get; set; }
    }

    public class MedicDetailModel
    {
        public string UserId { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        [Display(Name = "Fyzioterapie funkčních poruch")]
        public bool Spec1 { get; set; }
        [Display(Name = "Fyzio po úrazech a operacích")]
        public bool Spec2 { get; set; }
        [Display(Name = "Fyzio dětí")]
        public bool Spec3 { get; set; }
        [Display(Name = "Fyzio neurologických diagnóz")]
        public bool Spec4 { get; set; }
        [Display(Name = "Fyzio gerontů")]
        public bool Spec5 { get; set; }
        [Display(Name = "Home Fyzio")]
        public bool Spec6 { get; set; }
        public string IdentifyNo { get; set; }
        public string TaxIdentifyNo { get; set; }
        public string BankAccount { get; set; }
        public string InvoiceAddress { get; set; }
        public string InvoiceEmail { get; set; }
        public string InvoicePhone { get; set; }

        public List<DashboardOfficeDetailModel> Offices { get; set; }
        virtual public List<ContactHistory> History { get; set; }
        public string NewText { get; set; }
    }

    public class DashboardOfficeDetailModel
    {
        public int Id { get; set; }
        public string UserId { get; set; }

        [Required(ErrorMessage = "Název ordinace musí být vyplněn")]
        [MaxLength(64)]
        public string Name { get; set; }

        [Required(ErrorMessage = "Položka Ulice musí být vyplněna")]
        [MaxLength(128)]
        public string Street { get; set; }

        [Required(ErrorMessage = "Položka Číslo popisné musí být vyplněna")]
        [MaxLength(8)]
        public string StreetNo { get; set; }

        [Required(ErrorMessage = "Položka PSČ musí být vyplněna")]
        [RegularExpression("([0-9]*)", ErrorMessage = "Položka PSČ obsahuje neplatné znaky")]
        [MaxLength(5)]
        public string PostalCode { get; set; }

        [Required(ErrorMessage = "Položka Město musí být vyplněna")]
        [MaxLength(128)]
        public string City { get; set; }

        [Required(ErrorMessage = "Položka Země musí být vyplněna")]
        [MaxLength(128)]
        public string Country { get; set; }
        public string Latitude { get; set; }
        public string Longitude { get; set; }
        [RegularExpression("([1-9][0-9]*)", ErrorMessage = "Telefonní číslo obsahuje chyby")]
        public string Phone { get; set; }
        //public List<SelectListItem> PhonePrefixList { get; set; }
        //public string PhonePrefix { get; set; }
        //public int PhonePrefixLength { get; set; }
        public int Price30 { get; set; }
        public int Price60 { get; set; }
        public int Price90 { get; set; }
    }

    public class AllEmailsModel
    {
        public List<EmailModel> Emails { get; set; }
    }

    public class EmailModel
    {
        public string Email { get; set; }
        public string Invited { get; set; }
        public string Inserted { get; set; }
    }
    public class EmailDetailModel
    {
        public string Email { get; set; }
        public string Invited { get; set; }
        public string Inserted { get; set; }
        virtual public List<ContactHistory> History { get; set; }
        public string NewText { get; set; }
    }

    public class ContactHistory
    {
        public string Date { get; set; }
        public string UserLogin { get; set; }
        public string Text { get; set; }
    }

    public class AllMessagesModel
    {
        public List<MessageModel> Messages { get; set; }
    }

    public class MessageModel
    {
        public string Date { get; set; }
        public string Email { get; set; }
        public string Text { get; set; }
        public string Description { get; set; }
    }

    public class AllLogsModel
    {
        public List<LogModel> Logs { get; set; }
    }

    public class LogModel
    {
        public string UserId { get; set; }
        public string Date { get; set; }
        public string Level { get; set; }
        public string Info { get; set; }
        public string Description { get; set; }
    }

    public class AllPatientNewslettersModel
    {
        public List<string> Emails { get; set; }
    }

    public class WatchdogModel
    {
        public string Email { get; set; }
        public string Name { get; set; }
    }

    public class AllWatchdogsModel
    {
        public List<WatchdogModel> Watchdogs { get; set; }
    }
}

SosBodyApp/Controllers/DashboardController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SosBody.Models;
using System.Threading.Tasks;
using System.Data.Entity.Core.Objects;
using System.Data.SqlClient;
using SosBody.Infrastructure;
using Microsoft.AspNet.Identity.Owin;
using Microsoft.AspNet.Identity;
using SOSBody.Helpers;
using System.IO;

namespace SOSBody.Controllers
{
    [Authorize(Roles = "SOSBodyAdmin")]
    public class DashboardController : Controller
    {
        IdentityDbEntities db = new IdentityDbEntities();
        private static Logger logger = new Logger();
        private static PhoneHelper ph = new PhoneHelper();

        private AppRoleManager RoleManager
        {
            get
            {
                return HttpContext.GetOwinContext().GetUserManager<AppRoleManager>();
            }
        }

        public ActionResult Index(string sortOrder)
        {
            ViewBag.Name = "name";
            ViewBag.LastName = "lastname";
            ViewBag.Personal = "personal_desc";
            ViewBag.Office = "office_desc";
            ViewBag.Invoice = "invoice_desc";
            ViewBag.ProfileImage = "image_desc";

            var allMedics = db.AspNetUsers.ToList();

            AllMedicsModel allMedicsModel = new AllMedicsModel()
            {
                Medics = new List<BasicMedicsModel>()
            };

            int completedRegs = 0;
            int incompletedRegs = 0;        

            AppRole role = RoleManager.FindByName("SOSBodyMedic");
            var users = role.Users.ToList();

            foreach (var entity in users)
            {
                var medicDetail = db.MedicDetails.Where(x => x.UserId == entity.UserId).FirstOrDefault();
                var historyDetail = db.DashboardHistory.ToList();
                DashboardHistory history = null;
                if(medicDetail != null)
                    history = historyDetail.Where(x => x.UserLogin == medicDetail.Email).LastOrDefault();

                BasicMedicsModel model = new BasicMedicsModel()
                {
                    UserId = entity.UserId,
                    Name = medicDetail?.Name,
                    LastName = medicDetail?.Lastname,
                    IsProfileImage = IsProfileImage(Globals.ProfileImagesPath, entity.UserId),
                    IsMedicPersonalData = IsMedicPersonalProfileCreated(entity.UserId),
                    IsMedicOfficeData = IsMedicOfficeCreated(entity.UserId),
                    IsMedicInviceData = IsMedicInvoiceDataCreated(entity.UserId),
                    FreeDates = GetFreeDatesCount(entity.UserId),
                    TotalDates = GetDatesTotalCount(entity.UserId),
                    TotalOrders = GetOrderedDatesTotalCount(entity.UserId),
                    Email = medicDetail?.Email,
                    Phone = ph.GetPhonePrefix(medicDetail?.Phone) + ph.GetPhonePure(medicDetail?.Phone),
                    LastHistoryPost = history?.Text //(history != null) ? history.Text.Substring(0, Math.Min(history.Text.Length, 100)) : "",
                };

                if (model.IsMedicInviceData && model.IsMedicOfficeData && model.IsMedicPersonalData)
                    completedRegs++;
                else
                    incompletedRegs++;

                allMedicsModel.Medics.Add(model);
            }

            allMedicsModel.CompletedRegistrations = completedRegs;
            allMedicsModel.IncompletedRegistrations = incompletedRegs;

            switch (sortOrder)
            {
                case "name":
                    allMedicsModel.Medics = allMedicsModel.Medics.OrderBy(s => s.Name).ToList();
                    ViewBag.Name = "name_desc";
                    break;
                case "name_desc":
                    allMedicsModel.Medics = allMedicsModel.Medics.OrderByDescending(s => s.Name).ToList();
                    ViewBag.Name = "name";
                    break;
                case "lastname":
                    allMedicsModel.Medics = allMedicsModel.Medics.OrderBy(s => s.LastName).ToList();
                    ViewBag.LastName = "lastname_desc";
                    break;
                case "lastname_desc":
                    allMedicsModel.Medics = allMedicsModel.Medics.OrderByDescending(s => s.LastName).ToList();
                    ViewBag.LastName = "lastname";
                    break;
                case "personal_desc":
                    allMedicsModel.Medics = allMedicsModel.Medics.OrderByDescending(s => s.IsMedicPersonalData).ToList();
                    ViewBag.Personal = "personal";
                    break;
                case "personal":
                    allMedicsModel.Medics = allMedicsModel.Medics.OrderBy(s => s.IsMedicPersonalData).ToList();
                    ViewBag.Personal = "personal_desc";
                    break;
                case "office_desc":
                    allMedicsModel.Medics = allMedicsModel.Medics.OrderByDescending(s => s.IsMedicOfficeData).ToList();
                    ViewBag.Office = "office";
                    break;
                case "office":
                    allMedicsModel.Medics = allMedicsModel.Medics.OrderBy(s => s.IsMedicOfficeData).ToList();
                    ViewBag.Office = "office_desc";
                    break;
                case "invoice_desc":
                    allMedicsModel.Medics = allMedicsModel.Medics.OrderByDescending(s => s.IsMedicInviceData).ToList();
                    ViewBag.Invoice = "invoice";
                    break;
                case "invoice":
                    allMedicsModel.Medics = allMedicsModel.Medics.OrderBy(s => s.IsMedicInviceData).ToList();
                    ViewBag.Invoice = "invoice_desc";
                    break;
                case "image_desc":
                    allMedicsModel.Medics = allMedicsModel.Medics.OrderByDescending(s => s.IsProfileImage).ToList();
                    ViewBag.ProfileImage = "image";
                    break;
                case "image":
                    allMedicsModel.Medics = allMedicsModel.Medics.OrderBy(s => s.IsProfileImage).ToList();
                    ViewBag.ProfileImage = "image_desc";
                    break;
                default:
                    break;
            }

            return View(allMedicsModel);
        }

        private bool IsMedicPersonalProfileCreated(string userId)
        {
            var medicDetail = db.MedicDetails.Where(x => x.UserId == userId);
            if (medicDetail == null || medicDetail.Count() == 0)
                return false;

            return true;
        }

        private bool IsMedicOfficeCreated(string userId)
        {
            var officeDetail = db.OfficeDetails.Where(x => x.UserId == userId);
            if (officeDetail == null || officeDetail.Count() == 0)
                return false;

            return true;
        }

        private bool IsMedicInvoiceDataCreated(string userId)
        {
            var invoiceDetail = db.MedicInvoiceDetails.Where(x => x.UserId == userId);
            if (invoiceDetail == null || invoiceDetail.Count() == 0)
                return false;

            return true;
        }

        private bool IsProfileImage(string dir, string UserId)
        {
            string directory = Server.MapPath(dir);
            string[] fileEntries = Directory.GetFiles(directory);
            foreach (string fileName in fileEntries)
            {
                int lastSlashPos = fileName.LastIndexOf('\\');
                string name = fileName.Substring(lastSlashPos + 1);
                int lastComaPos = name.LastIndexOf('.');
                string subName = name.Substring(0, lastComaPos);

                if (subName == UserId)
                    return true;
            }

            return false;
        }

        protected int GetFreeDatesCount(string userId)
        {
            var dates = db.Calendar.Where(x => x.UserId == userId && x.Date >= DateTime.Now);
            if (dates == null)
                return 0;

            return dates.ToList().Count;
        }

        protected int GetDatesTotalCount(string userId)
        {
            return db.Calendar.Where(x => x.UserId == userId).ToList().Count;
        }

        protected int GetOrderedDatesTotalCount(string userId)
        {
            var orders = db.Orders.Where(x => x.MedicId == userId).ToList();
            int totalCount = 0;
            foreach(Order order in orders)
            {
                var payment = db.Payments.Where(x => x.OrderId == order.Id && x.Status == "PAID").FirstOrDefault();
                if (payment != null)
                    totalCount++;
            }

            return totalCount;
        }

        public ActionResult MedicDetail(string userId)
        {
            MedicDetailModel model = new MedicDetailModel()
            {
                Offices = new List<DashboardOfficeDetailModel>()
            };

            var medicDetail = db.MedicDetails.Where(x => x.UserId == userId).FirstOrDefault();

            model.Name = medicDetail?.Title + " " + medicDetail?.Name + " " + medicDetail?.Lastname + " " + medicDetail?.TitleBehind;
            model.Email = medicDetail?.Email;
            model.Phone = medicDetail?.Phone.Replace('-', ' ');
            model.Spec1 = medicDetail == null ? false : medicDetail.Spec1;
            model.Spec2 = medicDetail == null ? false : medicDetail.Spec2;
            model.Spec3 = medicDetail == null ? false : medicDetail.Spec3;
            model.Spec4 = medicDetail == null ? false : medicDetail.Spec4;
            model.Spec5 = medicDetail == null ? false : medicDetail.Spec5;
            model.Spec6 = medicDetail == null ? false : medicDetail.Spec6;

            var invoiceDetail = db.MedicInvoiceDetails.Where(x => x.UserId == userId).FirstOrDefault();

            model.IdentifyNo = invoiceDetail?.IdentifyNo;
            model.TaxIdentifyNo = invoiceDetail?.TaxIdentifyNo;

SosBodyApp/Views/Dashboard/EmailDetail.cshtml
@using SosBody.Models;
@model SosBody.Models.EmailDetailModel
@{
    ViewBag.Title = "SOS Body";
}


@section menuItems {
    @Html.ActionLink("ODHLÁSIT SE", "Logout", "Account", null, new { @class = "w3-bar-item w3-button w3-padding-large " })
}


<!-- Page content -->
<div class="w3-container w3-content w3-padding-64" style="max-width:600px" id="contact">
    <div class="w3-row w3-padding-32 sos-tabs">
        <div class="w3-center">
            @Html.ActionLink("FYZIOTERAPEUTI", "Index", "Dashboard", null, new { @class = "" })
        </div>
        <div class="w3-center">
            @Html.ActionLink("EMAILY", "Emails", "Dashboard", null, new { @class = "" })
        </div>
        @*<div class="w3-center">
            @Html.ActionLink("LOGY", "Logs", "Dashboard", null, new { @class = "" })
        </div>
        <div class="w3-center">
            @Html.ActionLink("NEWSLETTERY", "PatientNewsletters", "Dashboard", null, new { @class = "" })
        </div>
        <div class="w3-center">
            @Html.ActionLink("HLÍDACÍ PES", "Watchdogs", "Dashboard", null, new { @class = "" })
        </div>
        <div class="w3-center">
            @Html.ActionLink("VZKAZY", "Messages", "Dashboard", null, new { @class = "" })
        </div>*@
    </div>

    <div class="w3-row w3-padding-32">
        <div class="w3-col color-gray w3-center" style="width:600px;">
            @using (Html.BeginForm())
            {
                @Html.HiddenFor(x => x.Inserted)
                @Html.HiddenFor(x => x.Invited)

                <div class="w3-row-padding medic-schedule-wrapper" style="margin:0 -16px 8px -16px;">
                    <h3>
                        Detail
                    </h3>
                    <div style="background-color:#73ac24;height:1px;width:100%;margin-bottom:10px;"></div>
                    <div class="w3-row-padding" style="margin:0 -16px 8px -16px">
                        <div class="w3-third left_col">
                            E-mail:
                        </div>
                        <div class="w3-twothird right_col">
                            @Model.Email
                        </div>
                    </div>
                    <div class="w3-row-padding" style="margin:0 -16px 8px -16px">
                        <div class="w3-third left_col">
                            Vloženo do SOS Body:
                        </div>
                        <div class="w3-twothird right_col">
                            @Model.Inserted
                        </div>
                    </div>
                    <div class="w3-row-padding" style="margin:0 -16px 8px -16px">
                        <div class="w3-third left_col">
                            Odeslán MailChimp:
                        </div>
                        <div class="w3-twothird right_col">
                            @Model.Invited
                        </div>
                    </div>
                    
                    <h3>
                        Historie kontaktu
                    </h3>
                    <div style="background-color:#73ac24;height:1px;width:100%;margin-bottom:10px;"></div>

                    @foreach (var item in Model.History)
                    {
                        <div class="w3-row-padding" style="margin:0 -16px 8px -16px">
                            <div class="w3-third left_col">
                                @item.Date
                            </div>
                            <div class="w3-twothird right_col">
                                @item.Text
                            </div>
                        </div>
                    }

                    <br />
                    @Html.TextAreaFor(x => x.NewText, htmlAttributes: new { @class = "reg_form", @style = "height:150px;" })
                    <br /><br />
                    <button type="submit" class="button">VLOŽIT</button>
                </div>
            }
        </div>
    </div>
</div>

SosBodyApp/Views/Dashboard/Emails.cshtml
@using SosBody.Models;
@model SosBody.Models.AllEmailsModel
@{
    ViewBag.Title = "SOS Body";
}


@section menuItems {
    @Html.ActionLink("ODHLÁSIT SE", "Logout", "Account", null, new { @class = "w3-bar-item w3-button w3-padding-large " })
}


<!-- Page content -->
<div class="w3-container w3-content w3-padding-64" style="max-width:800px" id="contact">
    <div class="w3-row w3-padding-32 sos-tabs">
        <div class="w3-center">
            @Html.ActionLink("FYZIOTERAPEUTI", "Index", "Dashboard", null, new { @class = "" })
        </div>
        <div class="w3-center">
            @Html.ActionLink("E-MAILY", "Emails", "Dashboard", null, new { @class = "current" })
        </div>
        @*<div class="w3-center">
            @Html.ActionLink("LOGY", "Logs", "Dashboard", null, new { @class = "" })
        </div>
        <div class="w3-center">
            @Html.ActionLink("NEWSLETTERY", "PatientNewsletters", "Dashboard", null, new { @class = "" })
        </div>
        <div class="w3-center">
            @Html.ActionLink("HLÍDACÍ PES", "Watchdogs", "Dashboard", null, new { @class = "" })
        </div>
        <div class="w3-center">
            @Html.ActionLink("VZKAZY", "Messages", "Dashboard", null, new { @class = "" })
        </div>*@
    </div>

    <div class="w3-row w3-padding-32">
        <div class="w3-col color-gray">
            @using (Html.BeginForm())
            {
                <div class="w3-row-padding medic-schedule-wrapper" style="margin:0 -16px 8px -16px;">
                    <h3>
                        Emaily fyzioterapeutů zadané přes webový formulář
                    </h3>
                    @*<div style="background-color:#73ac24;height:1px;width:100%;margin-bottom:10px;"></div>*@
                    <table class="medic-schedule">
                        <thead>
                            <tr>
                                <th></th>
                                <th>E-mail</th>
                                <th>Vloženo</th>
                                <th>Odeslán MailChimp</th>
                            </tr>
                        </thead>
                        <tbody>
                            @{ 
                                int lineNumber = 1;
                                foreach (var email in Model.Emails)
                                {
                                    <tr>
                                        <td>
                                            @lineNumber.
                                        </td>
                                        <td width="300">
                                            @email.Email
                                        </td>
                                        <td width="150">
                                            @email.Inserted
                                        </td>
                                        <td width="150">
                                            @email.Invited
                                        </td>
                                        <td>
                                            @Html.ActionLink("Detail", "EmailDetail", "Dashboard", new { email = @email.Email }, null)
                                        </td>
                                    </tr>
                                    lineNumber++;
                                }
                            }
                        </tbody>
                    </table>
                </div>
            }
        </div>
    </div>
</div>

SosBodyApp/Views/Dashboard/Index.cshtml
@using SosBody.Models;
@model SosBody.Models.AllMedicsModel
@{
    ViewBag.Title = "SOS Body";
}


@section menuItems {
    @Html.ActionLink("ODHLÁSIT SE", "Logout", "Account", null, new { @class = "w3-bar-item w3-button w3-padding-large " })
}


<!-- Page content -->
<div class="w3-container w3-content w3-padding-64" style="max-width:100%" id="contact">
    <div class="w3-row w3-padding-32 sos-tabs">
        <div class="w3-center">
            @Html.ActionLink("FYZIOTERAPEUTI", "Index", "Dashboard", null, new { @class = "current" })
        </div>
        <div class="w3-center">
            @Html.ActionLink("E-MAILY", "Emails", "Dashboard", null, new { @class = " " })
        </div>
        @*<div class="w3-center">
            @Html.ActionLink("LOGY", "Logs", "Dashboard", null, new { @class = "" })
        </div>
        <div class="w3-center">
            @Html.ActionLink("NEWSLETTERY", "PatientNewsletters", "Dashboard", null, new { @class = "" })
        </div>
        <div class="w3-center">
            @Html.ActionLink("HLÍDACÍ PES", "Watchdogs", "Dashboard", null, new { @class = "" })
        </div>
        <div class="w3-center">
            @Html.ActionLink("VZKAZY", "Messages", "Dashboard", null, new { @class = "" })
        </div>*@
    </div>

    <div class="w3-row">
        <div class="w3-left w3-left-align">
            Počet registrovaných: @Model.CompletedRegistrations
            <br />
            Počet nedokončených registrací: @Model.IncompletedRegistrations
        </div>
    </div>

    <div class="w3-row w3-padding-32">
        <div class="w3-col color-gray">
            @using (Html.BeginForm())
            {
                <div class="w3-row-padding medic-schedule-wrapper" style="margin:0 -16px 8px -16px;">
                    <h3>
                        Registrovaní fyzioterapeuti
                    </h3>
                    <table class="medic-schedule">
                        <thead>
                            <tr>
                                <th></th>
                                <th><strong>@Html.ActionLink("Jméno", "Index", new { sortOrder = ViewBag.Name })</strong></th>
                                <th><strong>@Html.ActionLink("Příjmení", "Index", new { sortOrder = ViewBag.LastName })</strong></th>
                                <th style="text-align:center;"><strong>@Html.ActionLink("Základní údaje", "Index", new { sortOrder = ViewBag.Personal })</strong></th>
                                <th style="text-align:center;"><strong>@Html.ActionLink("Ordinace", "Index", new { sortOrder = ViewBag.Office })</strong></th>
                                <th style="text-align:center;"><strong>@Html.ActionLink("Fakturační údaje", "Index", new { sortOrder = ViewBag.Invoice })</strong></th>
                                <th style="text-align:center;"><strong>@Html.ActionLink("Fotografie", "Index", new { sortOrder = ViewBag.ProfileImage })</strong></th>
                                <th style="text-align:center;">Volné termíny</th>
                                <th style="text-align:center;">Rezervované termíny</th>
                                <th style="text-align:center;">E-mail</th>
                                <th style="text-align:center;">Telefon</th>
                                <th>Poznámka</th>
                                <th><strong></strong></th>
                            </tr>
                        </thead>
                        <tbody>
                            @{ 
                                int lineNumber = 1;
                                foreach (var medic in Model.Medics)
                                {
                                    <tr>
                                        <td>
                                            @lineNumber.
                                        </td>
                                        <td>
                                            @medic.Name
                                        </td>
                                        <td>
                                            @medic.LastName
                                        </td>
                                        <td align="center">
                                            @if (@medic.IsMedicPersonalData)
                                            {
                                                <img src="~/Images/ok_16x16.png" />
                                            }
                                            else
                                            {
                                                <img src="~/Images/cancel_16x16.png" />
                                            }
                                        </td>
                                        <td align="center">
                                            @if (@medic.IsMedicOfficeData)
                                            {
                                                <img src="~/Images/ok_16x16.png" />
                                            }
                                            else
                                            {
                                                <img src="~/Images/cancel_16x16.png" />
                                            }
                                        </td>
                                        <td align="center">
                                            @if (@medic.IsMedicInviceData)
                                            {
                                                <img src="~/Images/ok_16x16.png" />
                                            }
                                            else
                                            {
                                                <img src="~/Images/cancel_16x16.png" />
                                            }
                                        </td>
                                        <td align="center">
                                            @if (medic.IsProfileImage)
                                            {
                                                <img src="~/Images/ok_16x16.png" />
                                            }
                                            else
                                            {
                                                <img src="~/Images/cancel_16x16.png" />
                                            }
                                        </td>
                                        <td style="text-align:center;">
                                            @medic.FreeDates
                                        </td>
                                        <td style="text-align:center;">@medic.TotalOrders/@medic.TotalDates </td>
                                        <td style="text-align:center;">
                                            @medic.Email
                                        </td>
                                        <td style="text-align:center;">
                                            @medic.Phone
                                        </td>
                                        <td>
                                            @medic.LastHistoryPost
                                        </td>
                                        <td width="100">
                                            @Html.ActionLink("Detail", "MedicDetail", "Dashboard", new { userId = @medic.UserId }, null)
                                        </td>
                                    </tr>
                                    lineNumber++;
                                }
                             }
                         </tbody>
                    </table>
                </div>
            }
        </div>
    </div>
</div>